version: '3'
services:
  master:
    build: ./app
    container_name: "master"
    hostname: "master"
    depends_on:
      - consul
    command: "m 200"
  worker:
    build: ./app
    depends_on:
      - master
    command: "w 10"
  consul:
    image: "consul:latest"
    container_name: "consul"
    hostname: "consul"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "agent -server -bootstrap -ui -disable-host-node-id -client 0.0.0.0"